spring.application.name=attendance-system
server.port=${PORT:8080}
admin.id=${ADMIN_ID:}
admin.password=${ADMIN_PASSWORD:}
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:attendance-system;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/db/schema-postgres.sql
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
