spring.application.name=attendance-system
server.port=${PORT:8080}
spring.datasource.url=${DATABASE_URL:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/db/schema-postgres.sql
spring.sql.init.data-locations=classpath:/db/data-members.sql
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
